# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a41e71466cd7a13f28c3f9c0008a95d164db6667c0a6d2c52ef9cf14b25836757d4176e831ac602cfdf06bd02e3a4b0a4df26157975460fe14b42dabe8b6cf58

test:
  secret_key_base: 98d81390d5cd4638289fa6871df7b27ff343e683050016155ad972f625c280401032085caf5164dbc4a58258342faab9f3a3fee961249c804a00d95c34130bf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
